export interface SurahMeta {
  number: number;
  name: string;
  englishName: string;
  englishNameTranslation: string;
  revelationType: "Meccan" | "Medinan";
  numberOfAyahs: number;
  startPage: number;
  endPage: number;
}

export interface JuzMeta {
  index: number;
  startSurah: number;
  startAyah: number;
  startPage: number;
  name: string;
}

export const SURAH_LIST: SurahMeta[] = [
  { number: 1, name: "الفَاتِحَة", englishName: "Al-Fatihah", englishNameTranslation: "The Opener", revelationType: "Meccan", numberOfAyahs: 7, startPage: 1, endPage: 1 },
  { number: 2, name: "البَقَرَة", englishName: "Al-Baqarah", englishNameTranslation: "The Cow", revelationType: "Medinan", numberOfAyahs: 286, startPage: 2, endPage: 49 },
  { number: 3, name: "آلِ عِمْرَان", englishName: "Ali 'Imran", englishNameTranslation: "Family of Imran", revelationType: "Medinan", numberOfAyahs: 200, startPage: 50, endPage: 76 },
  { number: 4, name: "النِّسَاء", englishName: "An-Nisa", englishNameTranslation: "The Women", revelationType: "Medinan", numberOfAyahs: 176, startPage: 77, endPage: 106 },
  { number: 5, name: "المَائِدَة", englishName: "Al-Ma'idah", englishNameTranslation: "The Table Spread", revelationType: "Medinan", numberOfAyahs: 120, startPage: 106, endPage: 127 },
  { number: 6, name: "الأَنْعَام", englishName: "Al-An'am", englishNameTranslation: "The Cattle", revelationType: "Meccan", numberOfAyahs: 165, startPage: 128, endPage: 150 },
  { number: 7, name: "الأَعْرَاف", englishName: "Al-A'raf", englishNameTranslation: "The Heights", revelationType: "Meccan", numberOfAyahs: 206, startPage: 151, endPage: 176 },
  { number: 8, name: "الأَنْفَال", englishName: "Al-Anfal", englishNameTranslation: "The Spoils of War", revelationType: "Medinan", numberOfAyahs: 75, startPage: 177, endPage: 186 },
  { number: 9, name: "التَّوْبَة", englishName: "At-Tawbah", englishNameTranslation: "The Repentance", revelationType: "Medinan", numberOfAyahs: 129, startPage: 187, endPage: 207 },
  { number: 10, name: "يُونُس", englishName: "Yunus", englishNameTranslation: "Jonah", revelationType: "Meccan", numberOfAyahs: 109, startPage: 208, endPage: 221 },
  { number: 11, name: "هُود", englishName: "Hud", englishNameTranslation: "Hud", revelationType: "Meccan", numberOfAyahs: 123, startPage: 221, endPage: 235 },
  { number: 12, name: "يُوسُف", englishName: "Yusuf", englishNameTranslation: "Joseph", revelationType: "Meccan", numberOfAyahs: 111, startPage: 235, endPage: 248 },
  { number: 13, name: "الرَّعْد", englishName: "Ar-Ra'd", englishNameTranslation: "The Thunder", revelationType: "Medinan", numberOfAyahs: 43, startPage: 249, endPage: 255 },
  { number: 14, name: "إِبْرَاهِيم", englishName: "Ibrahim", englishNameTranslation: "Abrahim", revelationType: "Meccan", numberOfAyahs: 52, startPage: 255, endPage: 261 },
  { number: 15, name: "الحِجْر", englishName: "Al-Hijr", englishNameTranslation: "The Rocky Tract", revelationType: "Meccan", numberOfAyahs: 99, startPage: 262, endPage: 267 },
  { number: 16, name: "النَّحْل", englishName: "An-Nahl", englishNameTranslation: "The Bee", revelationType: "Meccan", numberOfAyahs: 128, startPage: 267, endPage: 281 },
  { number: 17, name: "الإِسْرَاء", englishName: "Al-Isra", englishNameTranslation: "The Night Journey", revelationType: "Meccan", numberOfAyahs: 111, startPage: 282, endPage: 293 },
  { number: 18, name: "الكَهْف", englishName: "Al-Kahf", englishNameTranslation: "The Cave", revelationType: "Meccan", numberOfAyahs: 110, startPage: 293, endPage: 304 },
  { number: 19, name: "مَرْيَم", englishName: "Maryam", englishNameTranslation: "Mary", revelationType: "Meccan", numberOfAyahs: 98, startPage: 305, endPage: 312 },
  { number: 20, name: "طه", englishName: "Taha", englishNameTranslation: "Ta-Ha", revelationType: "Meccan", numberOfAyahs: 135, startPage: 312, endPage: 321 },
  { number: 21, name: "الأَنْبِيَاء", englishName: "Al-Anbiya", englishNameTranslation: "The Prophets", revelationType: "Meccan", numberOfAyahs: 112, startPage: 322, endPage: 331 },
  { number: 22, name: "الحَجّ", englishName: "Al-Hajj", englishNameTranslation: "The Pilgrimage", revelationType: "Medinan", numberOfAyahs: 78, startPage: 332, endPage: 341 },
  { number: 23, name: "المُؤْمِنُون", englishName: "Al-Mu'minun", englishNameTranslation: "The Believers", revelationType: "Meccan", numberOfAyahs: 118, startPage: 342, endPage: 349 },
  { number: 24, name: "النُّور", englishName: "An-Nur", englishNameTranslation: "The Light", revelationType: "Medinan", numberOfAyahs: 64, startPage: 350, endPage: 359 },
  { number: 25, name: "الفُرْقَان", englishName: "Al-Furqan", englishNameTranslation: "The Criterion", revelationType: "Meccan", numberOfAyahs: 77, startPage: 359, endPage: 366 },
  { number: 26, name: "الشُّعَرَاء", englishName: "Ash-Shu'ara", englishNameTranslation: "The Poets", revelationType: "Meccan", numberOfAyahs: 227, startPage: 367, endPage: 376 },
  { number: 27, name: "النَّمْل", englishName: "An-Naml", englishNameTranslation: "The Ant", revelationType: "Meccan", numberOfAyahs: 93, startPage: 377, endPage: 385 },
  { number: 28, name: "القَصَص", englishName: "Al-Qasas", englishNameTranslation: "The Stories", revelationType: "Meccan", numberOfAyahs: 88, startPage: 385, endPage: 396 },
  { number: 29, name: "العَنْكَبُوت", englishName: "Al-'Ankabut", englishNameTranslation: "The Spider", revelationType: "Meccan", numberOfAyahs: 69, startPage: 396, endPage: 404 },
  { number: 30, name: "الرُّوم", englishName: "Ar-Rum", englishNameTranslation: "The Romans", revelationType: "Meccan", numberOfAyahs: 60, startPage: 404, endPage: 410 },
  { number: 31, name: "لُقْمَان", englishName: "Luqman", englishNameTranslation: "Luqman", revelationType: "Meccan", numberOfAyahs: 34, startPage: 411, endPage: 414 },
  { number: 32, name: "السَّجْدَة", englishName: "As-Sajdah", englishNameTranslation: "The Prostration", revelationType: "Meccan", numberOfAyahs: 30, startPage: 415, endPage: 417 },
  { number: 33, name: "الأَحْزَاب", englishName: "Al-Ahzab", englishNameTranslation: "The Combined Forces", revelationType: "Medinan", numberOfAyahs: 73, startPage: 418, endPage: 427 },
  { number: 34, name: "سَبَأ", englishName: "Saba", englishNameTranslation: "Sheba", revelationType: "Meccan", numberOfAyahs: 54, startPage: 428, endPage: 434 },
  { number: 35, name: "فَاطِر", englishName: "Fatir", englishNameTranslation: "Originator", revelationType: "Meccan", numberOfAyahs: 45, startPage: 434, endPage: 440 },
  { number: 36, name: "يس", englishName: "Ya-Sin", englishNameTranslation: "Ya Sin", revelationType: "Meccan", numberOfAyahs: 83, startPage: 440, endPage: 445 },
  { number: 37, name: "الصَّافَّات", englishName: "As-Saffat", englishNameTranslation: "Those who set the Ranks", revelationType: "Meccan", numberOfAyahs: 182, startPage: 446, endPage: 452 },
  { number: 38, name: "ص", englishName: "Sad", englishNameTranslation: "The Letter Sad", revelationType: "Meccan", numberOfAyahs: 88, startPage: 453, endPage: 458 },
  { number: 39, name: "الزُّمَر", englishName: "Az-Zumar", englishNameTranslation: "The Troops", revelationType: "Meccan", numberOfAyahs: 75, startPage: 458, endPage: 467 },
  { number: 40, name: "غَافِر", englishName: "Ghafir", englishNameTranslation: "The Forgiver", revelationType: "Meccan", numberOfAyahs: 85, startPage: 467, endPage: 476 },
  { number: 41, name: "فُصِّلَت", englishName: "Fussilat", englishNameTranslation: "Explained in Detail", revelationType: "Meccan", numberOfAyahs: 54, startPage: 477, endPage: 482 },
  { number: 42, name: "الشُّورَى", englishName: "Ash-Shura", englishNameTranslation: "The Consultation", revelationType: "Meccan", numberOfAyahs: 53, startPage: 483, endPage: 489 },
  { number: 43, name: "الزُّخْرُف", englishName: "Az-Zukhruf", englishNameTranslation: "The Gold Adornment", revelationType: "Meccan", numberOfAyahs: 89, startPage: 489, endPage: 495 },
  { number: 44, name: "الدُّخَان", englishName: "Ad-Dukhan", englishNameTranslation: "The Smoke", revelationType: "Meccan", numberOfAyahs: 59, startPage: 496, endPage: 498 },
  { number: 45, name: "الجَاثِيَة", englishName: "Al-Jathiyah", englishNameTranslation: "The Crouching", revelationType: "Meccan", numberOfAyahs: 37, startPage: 499, endPage: 502 },
  { number: 46, name: "الأَحْقَاف", englishName: "Al-Ahqaf", englishNameTranslation: "The Wind-Curved Sandhills", revelationType: "Meccan", numberOfAyahs: 35, startPage: 502, endPage: 506 },
  { number: 47, name: "مُحَمَّد", englishName: "Muhammad", englishNameTranslation: "Muhammad", revelationType: "Medinan", numberOfAyahs: 38, startPage: 507, endPage: 510 },
  { number: 48, name: "الفَتْح", englishName: "Al-Fath", englishNameTranslation: "The Victory", revelationType: "Medinan", numberOfAyahs: 29, startPage: 511, endPage: 515 },
  { number: 49, name: "الحُجُرَات", englishName: "Al-Hujurat", englishNameTranslation: "The Rooms", revelationType: "Medinan", numberOfAyahs: 18, startPage: 515, endPage: 517 },
  { number: 50, name: "ق", englishName: "Qaf", englishNameTranslation: "The Letter Qaf", revelationType: "Meccan", numberOfAyahs: 45, startPage: 518, endPage: 520 },
  { number: 51, name: "الذَّارِيَات", englishName: "Adh-Dhariyat", englishNameTranslation: "The Winnowing Winds", revelationType: "Meccan", numberOfAyahs: 60, startPage: 520, endPage: 523 },
  { number: 52, name: "الطُّور", englishName: "At-Tur", englishNameTranslation: "The Mount", revelationType: "Meccan", numberOfAyahs: 49, startPage: 523, endPage: 525 },
  { number: 53, name: "النَّجْم", englishName: "An-Najm", englishNameTranslation: "The Star", revelationType: "Meccan", numberOfAyahs: 62, startPage: 526, endPage: 528 },
  { number: 54, name: "القَمَر", englishName: "Al-Qamar", englishNameTranslation: "The Moon", revelationType: "Meccan", numberOfAyahs: 55, startPage: 528, endPage: 531 },
  { number: 55, name: "الرَّحْمَٰن", englishName: "Ar-Rahman", englishNameTranslation: "The Beneficent", revelationType: "Medinan", numberOfAyahs: 78, startPage: 531, endPage: 534 },
  { number: 56, name: "الوَاقِعَة", englishName: "Al-Waqi'ah", englishNameTranslation: "The Inevitable", revelationType: "Meccan", numberOfAyahs: 96, startPage: 534, endPage: 537 },
  { number: 57, name: "الحَدِيد", englishName: "Al-Hadid", englishNameTranslation: "The Iron", revelationType: "Medinan", numberOfAyahs: 29, startPage: 537, endPage: 541 },
  { number: 58, name: "المُجَادِلَة", englishName: "Al-Mujadila", englishNameTranslation: "The Pleading Woman", revelationType: "Medinan", numberOfAyahs: 22, startPage: 542, endPage: 545 },
  { number: 59, name: "الحَشْر", englishName: "Al-Hashr", englishNameTranslation: "The Exile", revelationType: "Medinan", numberOfAyahs: 24, startPage: 545, endPage: 548 },
  { number: 60, name: "المُمْتَحِنَة", englishName: "Al-Mumtahanah", englishNameTranslation: "She that is to be examined", revelationType: "Medinan", numberOfAyahs: 13, startPage: 549, endPage: 551 },
  { number: 61, name: "الصَّفّ", englishName: "As-Saff", englishNameTranslation: "The Ranks", revelationType: "Medinan", numberOfAyahs: 14, startPage: 551, endPage: 552 },
  { number: 62, name: "الجُمُعَة", englishName: "Al-Jumu'ah", englishNameTranslation: "The Congregation, Friday", revelationType: "Medinan", numberOfAyahs: 11, startPage: 553, endPage: 554 },
  { number: 63, name: "المُنَافِقُون", englishName: "Al-Munafiqun", englishNameTranslation: "The Hypocrites", revelationType: "Medinan", numberOfAyahs: 11, startPage: 554, endPage: 556 },
  { number: 64, name: "التَّغَابُن", englishName: "At-Taghabun", englishNameTranslation: "The Mutual Disillusion", revelationType: "Medinan", numberOfAyahs: 18, startPage: 556, endPage: 557 },
  { number: 65, name: "الطَّلَاق", englishName: "At-Talaq", englishNameTranslation: "The Divorce", revelationType: "Medinan", numberOfAyahs: 12, startPage: 558, endPage: 559 },
  { number: 66, name: "التَّحْرِيم", englishName: "At-Tahrim", englishNameTranslation: "The Prohibition", revelationType: "Medinan", numberOfAyahs: 12, startPage: 560, endPage: 561 },
  { number: 67, name: "المُلْك", englishName: "Al-Mulk", englishNameTranslation: "The Sovereignty", revelationType: "Meccan", numberOfAyahs: 30, startPage: 562, endPage: 564 },
  { number: 68, name: "القَلَم", englishName: "Al-Qalam", englishNameTranslation: "The Pen", revelationType: "Meccan", numberOfAyahs: 52, startPage: 564, endPage: 566 },
  { number: 69, name: "الحَاقَّة", englishName: "Al-Haqqah", englishNameTranslation: "The Reality", revelationType: "Meccan", numberOfAyahs: 52, startPage: 566, endPage: 568 },
  { number: 70, name: "المَعَارِج", englishName: "Al-Ma'arij", englishNameTranslation: "The Ascending Stairways", revelationType: "Meccan", numberOfAyahs: 44, startPage: 568, endPage: 570 },
  { number: 71, name: "نُوح", englishName: "Nuh", englishNameTranslation: "Noah", revelationType: "Meccan", numberOfAyahs: 28, startPage: 570, endPage: 571 },
  { number: 72, name: "الجِنّ", englishName: "Al-Jinn", englishNameTranslation: "The Jinn", revelationType: "Meccan", numberOfAyahs: 28, startPage: 572, endPage: 573 },
  { number: 73, name: "المُزَّمِّل", englishName: "Al-Muzzammil", englishNameTranslation: "The Enshrouded One", revelationType: "Meccan", numberOfAyahs: 20, startPage: 573, endPage: 575 },
  { number: 74, name: "المُدَّثِّر", englishName: "Al-Muddaththir", englishNameTranslation: "The Cloaked One", revelationType: "Meccan", numberOfAyahs: 56, startPage: 575, endPage: 577 },
  { number: 75, name: "القِيَامَة", englishName: "Al-Qiyamah", englishNameTranslation: "The Resurrection", revelationType: "Meccan", numberOfAyahs: 40, startPage: 577, endPage: 578 },
  { number: 76, name: "الإِنْسَان", englishName: "Al-Insan", englishNameTranslation: "Man", revelationType: "Medinan", numberOfAyahs: 31, startPage: 578, endPage: 580 },
  { number: 77, name: "المُرْسَلَات", englishName: "Al-Mursalat", englishNameTranslation: "The Emissaries", revelationType: "Meccan", numberOfAyahs: 50, startPage: 580, endPage: 581 },
  { number: 78, name: "النَّبَأ", englishName: "An-Naba", englishNameTranslation: "The Tidings", revelationType: "Meccan", numberOfAyahs: 40, startPage: 582, endPage: 583 },
  { number: 79, name: "النَّازِعَات", englishName: "An-Nazi'at", englishNameTranslation: "Those who drag forth", revelationType: "Meccan", numberOfAyahs: 46, startPage: 583, endPage: 584 },
  { number: 80, name: "عَبَسَ", englishName: "'Abasa", englishNameTranslation: "He Frowned", revelationType: "Meccan", numberOfAyahs: 42, startPage: 585, endPage: 585 },
  { number: 81, name: "التَّكْوِير", englishName: "At-Takwir", englishNameTranslation: "The Overthrowing", revelationType: "Meccan", numberOfAyahs: 29, startPage: 586, endPage: 586 },
  { number: 82, name: "الانْفِطَار", englishName: "Al-Infitar", englishNameTranslation: "The Cleaving", revelationType: "Meccan", numberOfAyahs: 19, startPage: 587, endPage: 587 },
  { number: 83, name: "المُطَفِّفِين", englishName: "Al-Mutaffifin", englishNameTranslation: "The Defrauding", revelationType: "Meccan", numberOfAyahs: 36, startPage: 587, endPage: 589 },
  { number: 84, name: "الانْشِقَاق", englishName: "Al-Inshiqaq", englishNameTranslation: "The Sundering", revelationType: "Meccan", numberOfAyahs: 25, startPage: 589, endPage: 590 },
  { number: 85, name: "البُرُوج", englishName: "Al-Buruj", englishNameTranslation: "The Mansions of the Stars", revelationType: "Meccan", numberOfAyahs: 22, startPage: 590, endPage: 590 },
  { number: 86, name: "الطَّارِق", englishName: "At-Tariq", englishNameTranslation: "The Nightcommer", revelationType: "Meccan", numberOfAyahs: 17, startPage: 591, endPage: 591 },
  { number: 87, name: "الأَعْلَى", englishName: "Al-A'la", englishNameTranslation: "The Most High", revelationType: "Meccan", numberOfAyahs: 19, startPage: 591, endPage: 592 },
  { number: 88, name: "الغَاشِيَة", englishName: "Al-Ghashiyah", englishNameTranslation: "The Overwhelming", revelationType: "Meccan", numberOfAyahs: 26, startPage: 592, endPage: 592 },
  { number: 89, name: "الفَجْر", englishName: "Al-Fajr", englishNameTranslation: "The Dawn", revelationType: "Meccan", numberOfAyahs: 30, startPage: 593, endPage: 594 },
  { number: 90, name: "البَلَد", englishName: "Al-Balad", englishNameTranslation: "The City", revelationType: "Meccan", numberOfAyahs: 20, startPage: 594, endPage: 594 },
  { number: 91, name: "الشَّمْس", englishName: "Ash-Shams", englishNameTranslation: "The Sun", revelationType: "Meccan", numberOfAyahs: 15, startPage: 595, endPage: 595 },
  { number: 92, name: "اللَّيْل", englishName: "Al-Layl", englishNameTranslation: "The Night", revelationType: "Meccan", numberOfAyahs: 21, startPage: 595, endPage: 596 },
  { number: 93, name: "الضُّحَى", englishName: "Ad-Dhuha", englishNameTranslation: "The Morning Hours", revelationType: "Meccan", numberOfAyahs: 11, startPage: 596, endPage: 596 },
  { number: 94, name: "الشَّرْح", englishName: "Ash-Sharh", englishNameTranslation: "The Relief", revelationType: "Meccan", numberOfAyahs: 8, startPage: 596, endPage: 596 },
  { number: 95, name: "التِّين", englishName: "At-Tin", englishNameTranslation: "The Fig", revelationType: "Meccan", numberOfAyahs: 8, startPage: 597, endPage: 597 },
  { number: 96, name: "العَلَق", englishName: "Al-'Alaq", englishNameTranslation: "The Clot", revelationType: "Meccan", numberOfAyahs: 19, startPage: 597, endPage: 597 },
  { number: 97, name: "القَدْر", englishName: "Al-Qadr", englishNameTranslation: "The Power", revelationType: "Meccan", numberOfAyahs: 5, startPage: 598, endPage: 598 },
  { number: 98, name: "البَيِّنَة", englishName: "Al-Bayyinah", englishNameTranslation: "The Clear Proof", revelationType: "Medinan", numberOfAyahs: 8, startPage: 598, endPage: 599 },
  { number: 99, name: "الزَّلْزَلَة", englishName: "Az-Zalzalah", englishNameTranslation: "The Earthquake", revelationType: "Medinan", numberOfAyahs: 8, startPage: 599, endPage: 599 },
  { number: 100, name: "العَادِيَات", englishName: "Al-'Adiyat", englishNameTranslation: "The Courser", revelationType: "Meccan", numberOfAyahs: 11, startPage: 599, endPage: 600 },
  { number: 101, name: "القَارِعَة", englishName: "Al-Qari'ah", englishNameTranslation: "The Calamity", revelationType: "Meccan", numberOfAyahs: 11, startPage: 600, endPage: 600 },
  { number: 102, name: "التَّكَاثُر", englishName: "At-Takathur", englishNameTranslation: "The Rivalry in world increase", revelationType: "Meccan", numberOfAyahs: 8, startPage: 600, endPage: 600 },
  { number: 103, name: "العَصْر", englishName: "Al-'Asr", englishNameTranslation: "The Declining Day", revelationType: "Meccan", numberOfAyahs: 3, startPage: 601, endPage: 601 },
  { number: 104, name: "الهُمَزَة", englishName: "Al-Humazah", englishNameTranslation: "The Traducer", revelationType: "Meccan", numberOfAyahs: 9, startPage: 601, endPage: 601 },
  { number: 105, name: "الفِيل", englishName: "Al-Fil", englishNameTranslation: "The Elephant", revelationType: "Meccan", numberOfAyahs: 5, startPage: 601, endPage: 601 },
  { number: 106, name: "قُرَيْش", englishName: "Quraysh", englishNameTranslation: "Quraysh", revelationType: "Meccan", numberOfAyahs: 4, startPage: 602, endPage: 602 },
  { number: 107, name: "المَاعُون", englishName: "Al-Ma'un", englishNameTranslation: "The Small Kindnesses", revelationType: "Meccan", numberOfAyahs: 7, startPage: 602, endPage: 602 },
  { number: 108, name: "الكَوْثَر", englishName: "Al-Kawthar", englishNameTranslation: "The Abundance", revelationType: "Meccan", numberOfAyahs: 3, startPage: 602, endPage: 602 },
  { number: 109, name: "الكَافِرُون", englishName: "Al-Kafirun", englishNameTranslation: "The Disbelievers", revelationType: "Meccan", numberOfAyahs: 6, startPage: 603, endPage: 603 },
  { number: 110, name: "النَّصْر", englishName: "An-Nasr", englishNameTranslation: "The Divine Support", revelationType: "Medinan", numberOfAyahs: 3, startPage: 603, endPage: 603 },
  { number: 111, name: "المَسَد", englishName: "Al-Masad", englishNameTranslation: "The Palm Fiber", revelationType: "Meccan", numberOfAyahs: 5, startPage: 603, endPage: 603 },
  { number: 112, name: "الإِخْلَاص", englishName: "Al-Ikhlas", englishNameTranslation: "The Sincerity", revelationType: "Meccan", numberOfAyahs: 4, startPage: 604, endPage: 604 },
  { number: 113, name: "الفَلَق", englishName: "Al-Falaq", englishNameTranslation: "The Daybreak", revelationType: "Meccan", numberOfAyahs: 5, startPage: 604, endPage: 604 },
  { number: 114, name: "النَّاس", englishName: "An-Nas", englishNameTranslation: "Mankind", revelationType: "Meccan", numberOfAyahs: 6, startPage: 604, endPage: 604 },
];

export const JUZ_LIST: JuzMeta[] = [
  { index: 1, startSurah: 1, startAyah: 1, startPage: 1, name: "Juz' 1 — Al-Fatihah 1:1" },
  { index: 2, startSurah: 2, startAyah: 142, startPage: 22, name: "Juz' 2 — Al-Baqarah 2:142" },
  { index: 3, startSurah: 2, startAyah: 253, startPage: 42, name: "Juz' 3 — Al-Baqarah 2:253" },
  { index: 4, startSurah: 3, startAyah: 93, startPage: 62, name: "Juz' 4 — Ali 'Imran 3:93" },
  { index: 5, startSurah: 4, startAyah: 24, startPage: 82, name: "Juz' 5 — An-Nisa 4:24" },
  { index: 6, startSurah: 4, startAyah: 148, startPage: 102, name: "Juz' 6 — An-Nisa 4:148" },
  { index: 7, startSurah: 5, startAyah: 83, startPage: 122, name: "Juz' 7 — Al-Ma'idah 5:83" },
  { index: 8, startSurah: 6, startAyah: 111, startPage: 142, name: "Juz' 8 — Al-An'am 6:111" },
  { index: 9, startSurah: 7, startAyah: 88, startPage: 162, name: "Juz' 9 — Al-A'raf 7:88" },
  { index: 10, startSurah: 8, startAyah: 41, startPage: 182, name: "Juz' 10 — Al-Anfal 8:41" },
  { index: 11, startSurah: 9, startAyah: 93, startPage: 202, name: "Juz' 11 — At-Tawbah 9:93" },
  { index: 12, startSurah: 11, startAyah: 6, startPage: 222, name: "Juz' 12 — Hud 11:6" },
  { index: 13, startSurah: 12, startAyah: 53, startPage: 242, name: "Juz' 13 — Yusuf 12:53" },
  { index: 14, startSurah: 15, startAyah: 1, startPage: 262, name: "Juz' 14 — Al-Hijr 15:1" },
  { index: 15, startSurah: 17, startAyah: 1, startPage: 282, name: "Juz' 15 — Al-Isra 17:1" },
  { index: 16, startSurah: 18, startAyah: 75, startPage: 302, name: "Juz' 16 — Al-Kahf 18:75" },
  { index: 17, startSurah: 21, startAyah: 1, startPage: 322, name: "Juz' 17 — Al-Anbiya 21:1" },
  { index: 18, startSurah: 23, startAyah: 1, startPage: 342, name: "Juz' 18 — Al-Mu'minun 23:1" },
  { index: 19, startSurah: 25, startAyah: 21, startPage: 362, name: "Juz' 19 — Al-Furqan 25:21" },
  { index: 20, startSurah: 27, startAyah: 56, startPage: 382, name: "Juz' 20 — An-Naml 27:56" },
  { index: 21, startSurah: 29, startAyah: 46, startPage: 402, name: "Juz' 21 — Al-'Ankabut 29:46" },
  { index: 22, startSurah: 33, startAyah: 31, startPage: 422, name: "Juz' 22 — Al-Ahzab 33:31" },
  { index: 23, startSurah: 36, startAyah: 28, startPage: 442, name: "Juz' 23 — Ya-Sin 36:28" },
  { index: 24, startSurah: 39, startAyah: 32, startPage: 462, name: "Juz' 24 — Az-Zumar 39:32" },
  { index: 25, startSurah: 41, startAyah: 47, startPage: 482, name: "Juz' 25 — Fussilat 41:47" },
  { index: 26, startSurah: 46, startAyah: 1, startPage: 502, name: "Juz' 26 — Al-Ahqaf 46:1" },
  { index: 27, startSurah: 51, startAyah: 31, startPage: 522, name: "Juz' 27 — Adh-Dhariyat 51:31" },
  { index: 28, startSurah: 58, startAyah: 1, startPage: 542, name: "Juz' 28 — Al-Mujadila 58:1" },
  { index: 29, startSurah: 67, startAyah: 1, startPage: 562, name: "Juz' 29 — Al-Mulk 67:1" },
  { index: 30, startSurah: 78, startAyah: 1, startPage: 582, name: "Juz' 30 — An-Naba 78:1" },
];
